import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";

import Header from "../components/header";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const { push } = useRouter();
  const onGetStarted = () => {
    if (sessionData?.user !== undefined) {
      push('/admin/links');
    } else {
      signIn(undefined, { callbackUrl: `${window.location.origin}/admin/links` });
    }
  };

  //TODO: Make this page look nicer - see twitter bookmark.

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-y-10 p-2 md:p-6">
        <Header />
        <div className="flex flex-col items-center gap-y-10">
          <h1 className="text-5xl md:text-7xl lg:text-8xl text-center font-extrabold tracking-tight text-brandBlack">
            The <span className="text-brandBlue">open-source</span> <br />link displaying <span className="text-brandBlue">App</span>.
          </h1>
          <button
            className="text-white bg-brandBlue hover:bg-[#0576e5] duration-300 rounded-full w-fit px-10 py-3 text-xl font-semibold"
            onClick={onGetStarted}>Get Started</button>
        </div>
      </div>
    </>
  );
};

export default Home;
